language: java
sudo: false
dist: xenial
install: true

services:
  - xvfb

addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0

script:
  - mvn test
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn sonar:sonar; fi
